name: ${name}
main: ${package}.${name}
version: ${version}
authors: [Ghost_chu]
description: QSRR's Towny Addon
depend: [QuickShop,Towny]

api-version: 1.13

permissions:
    quickshop.addon.towny.bypass:
        description: Allows a player create shop out of towny COMMERCIAL plot
        default: op